version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:8080"
    environment:
      PYTHONUNBUFFERED: "True"
      SECRET_KEY: "secret_token"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
    volumes:
      - .:/app
